server:
    port: 8088

spring:
    application:
        name: auth-gateway
    cloud:
        gateway.server.webflux:
            routes:
                - id: auth-center
                  uri: http://localhost:8080
                  predicates:
                  - Path=/api/auth/**
                
                - id: user-service
                  uri: http://localhost:8082
                  predicates:
                  - Path=/api/user/**
                
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "http://localhost:5173"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                            - OPTIONS
                        allowedHeaders: "*"
                        allowCredentials: true
                        maxAge: 3600

app:
    jwt:
        secret: zkqbG3jiEd2Pbcm3xfGxnbcqdwdRKzMqBb1munHo82a  # TitHbLq0wbh9A8IeRkA9Sn3ZZt0hnUn15UN4caSDpqE
        issuer: auth_spring_gateway_jwt
        clock-skew-seconds: 30
    