# server:
#     port: PORT_NUMBER

# spring:
#     application:
#         name: YOUR_APP_NAME
#     Your gateway configuration

# app:
#     jwt:
#         your jwt configuration
        
                    
                    
